'use client';

import { useEffect, useState } from 'react';
import { request } from '@/lib/api';
import { ClientFAQ } from '@/types';
import { useLanguage } from '@/lib/i18n';
import { Loader2, HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';

interface PortalData {
  faq: ClientFAQ[];
}

export default function ClientFAQPage() {
  const { t, locale } = useLanguage();
  const [faqs, setFaqs] = useState<ClientFAQ[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [openId, setOpenId] = useState<string | null>(null);

  useEffect(() => {
    request<PortalData>('/clients/portal/data')
      .then((res: PortalData) => setFaqs(res.faq))
      .catch((err: any) => setError(err.message || 'Failed to load FAQ Q&A'))
      .finally(() => setLoading(false));
  }, []);

  const mockFaqs: ClientFAQ[] = [
    {
      id: 'mock-f-1',
      question: locale === 'ar' ? 'ما هو الجدول الزمني للموافقة على المحتوى؟' : "What is Sawaqly's content approval timeline?",
      answer: locale === 'ar' ? 'نقوم بإرسال المسودات للأسبوع القادم كل يوم أربعاء. لديك حتى بعد ظهر يوم الجمعة للموافقة عليها أو طلب تعديلات ليتم جدولتها في الوقت المحدد.' : 'We submit drafts for the upcoming week every Wednesday. You have until Friday afternoon to approve them or request edits so that they can be scheduled on time.',
      client_id: '1',
      sort_order: 1,
      created_at: '2026-07-01T00:00:00.000Z',
      updated_at: '2026-07-01T00:00:00.000Z'
    },
    {
      id: 'mock-f-2',
      question: locale === 'ar' ? 'كم مرة يتم تحديث تقارير أداء الحملة؟' : 'How often are campaign performance reports updated?',
      answer: locale === 'ar' ? 'تتزامن بياناتنا التسويقية تلقائياً في نهاية كل شهر. يتم إنشاء تقرير شهري شامل بواسطة مدير حسابك يعرض المشاهدات والتفاعل والتعليقات والرسائل.' : 'Our marketing data syncs automatically at the end of each month. A comprehensive monthly report is generated by your Account Manager showing views, interacts, comments, and messages.',
      client_id: '1',
      sort_order: 2,
      created_at: '2026-07-01T00:00:00.000Z',
      updated_at: '2026-07-01T00:00:00.000Z'
    },
    {
      id: 'mock-f-3',
      question: locale === 'ar' ? 'من يمكنني الاتصال به لطلبات النشر العاجلة؟' : 'Who can I contact for urgent post requests?',
      answer: locale === 'ar' ? 'لأي تعديلات عاجلة على المحتوى أو منشورات طارئة، يرجى استخدام بوابة المحادثة في لوحة التحكم الخاصة بك لمراسلة مدير حسابك المخصص مباشرة.' : 'For any urgent content modifications or emergency publications, please use the chat portal in your dashboard to message your dedicated Account Manager directly.',
      client_id: '1',
      sort_order: 3,
      created_at: '2026-07-01T00:00:00.000Z',
      updated_at: '2026-07-01T00:00:00.000Z'
    }
  ];

  const faqsToUse = faqs && faqs.length > 0 ? faqs : mockFaqs;

  const toggleOpen = (id: string) => {
    setOpenId(prev => (prev === id ? null : id));
  };

  return (
    <div className="flex flex-col gap-8 text-[#0F172A] text-start font-sans" dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      
      {/* Header */}
      <div className="border-b border-[#E2E8F0] pb-6">
        <h1 className="text-xl font-extrabold uppercase tracking-widest text-[#0F172A] font-mono">{t('portal.faqTitle')}</h1>
        <p className="text-[10px] text-[#64748B] uppercase tracking-wider font-semibold mt-1 text-start">{t('portal.faqDesc')}</p>
      </div>

      {loading ? (
        <div className="flex justify-center items-center py-20">
          <Loader2 className="size-5 animate-spin text-[#1D61E7]" />
        </div>
      ) : error ? (
        <div className="bg-red-50 border border-red-200 text-red-600 text-[10px] uppercase font-mono tracking-wider px-4 py-3 rounded-lg max-w-md mx-auto">
          {error}
        </div>
      ) : faqsToUse.length === 0 ? (
        <div className="border border-dashed border-[#E2E8F0] bg-white py-16 text-center rounded-2xl flex flex-col items-center justify-center gap-3 shadow-xs">
          <HelpCircle className="size-8 text-[#94A3B8]" />
          <h3 className="text-[10px] font-bold text-[#0F172A] uppercase tracking-widest font-mono">{t('portal.noFaq')}</h3>
          <p className="text-[10px] text-[#64748B] max-w-[320px] leading-relaxed uppercase tracking-wider font-semibold text-center">
            {t('portal.noFaqDesc')}
          </p>
        </div>
      ) : (
        <div className="flex flex-col gap-4 max-w-2xl mx-auto w-full">
          {faqsToUse.map(faq => {
            const isOpen = openId === faq.id;
            return (
              <div
                key={faq.id}
                className={`border bg-white transition-all rounded-2xl overflow-hidden shadow-xs ${
                  isOpen ? 'border-[#1D61E7] ring-1 ring-[#1D61E7]/25' : 'border-[#E2E8F0]'
                }`}
              >
                {/* Question trigger header */}
                <button
                  onClick={() => toggleOpen(faq.id)}
                  className="w-full px-5 py-4 flex items-center justify-between gap-4 text-start font-bold text-[10px] uppercase tracking-wider text-[#0F172A] hover:bg-slate-50 transition-colors font-mono"
                >
                  <span className={`leading-snug transition-colors ${isOpen ? 'text-[#1D61E7]' : ''}`}>{faq.question}</span>
                  {isOpen ? (
                     <ChevronUp className="size-4 text-[#FFD200] shrink-0" />
                  ) : (
                     <ChevronDown className="size-4 text-slate-400 shrink-0" />
                  )}
                </button>

                {/* Answer content (collapse pane) */}
                {isOpen && (
                  <div className="px-5 pb-5 pt-1.5 text-slate-600 text-xs leading-relaxed border-t border-[#E2E8F0] whitespace-pre-line text-start font-sans">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
